### ISSUE TITLE
watcher issues

### ISSUE THREAD

**Issue by Gitch70** [TannerGabriel/WebRTC-Video-Broadcast#10]
The watcher screen is just black with nothing on it (in Chrome on Win 7). You have to add 'controls' to the video tag, and then hit the play button on it. Not sure why you have to hit play because it has 'autoplay', but I have to anyway. Otherwise, nice!

**Comment by TannerGabriel** [comment]
I have never encountered this problem on Windows 10 or Linux. Still, I would be very interested if you find some kind of workaround for auto-playing the video without controls on Windows 7.

**Comment by Gitch70** [comment]
oddly, after the 1st half dozen or so times running it, it starts on it's own now. Weird.

thx,
b.
________________________________

**Comment by Gitch70** [comment]
hey btw, do you have any server code to actually save the video/audio file ?

thx,
b.
________________________________

**Comment by TannerGabriel** [comment]
No, I currently don't have any code to save the video and audio data in the repository.

**Comment by Gitch70** [comment]
ok thx anyway, maybe ffmpeg or something...

b.
________________________________

**Comment by Gitch70** [comment]
Hey quick question.

How come the viewing part works if i open it in a tab in the same browser instance. i.e. i open chrome, broadcast, then open another chrome tab and view and its fine. But, if I do the view part in IE or Chromium nothing shows up. Does it only work in Chrome? I see that if I open another chrome browser instance the viewing does work in it.

In chromium, trying to broadcast gives this error:

Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode on 'broadcast.js' file line 20.

IE gives a different error, big long one, and I can't seem to copy it from the DOM Explorer

thx,
b.
________________________________
