### ISSUE TITLE
error running localhost:4000/broadcast 

### ISSUE THREAD

**Issue by waqyun** [TannerGabriel/WebRTC-Video-Broadcast#14]
server started 
http://localhost:4000/broadcast gives error Cannot GET /broadcast

**Comment by AlexandreL0pes** [comment]
Have you tried to add .html in the url?
http://localhost:4000/broadcast.html

**Comment by waqyun** [comment]
> adding .html solves this.Thanks

**Comment by waqyun** [comment]
Yes that worked thanks a lot
