### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by piavgh** [TannerGabriel/WebRTC-Video-Broadcast#15]
**Describe the bug**
I tried to run this repository on both Ubuntu PC and a Macbook Pro (both docker and node server.js), but the sound can not be heard.

**To Reproduce**
1. Run the docker container
2. Go to localhost:4000/broadcast.html and say something
3. Open your phone and go to <ip-of-the-computer>:4000
4. Try to hear anything

**Expected behavior**
The sound of the broadcaster should be heard.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.15.6
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 83.0.4103.116

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Huawei Nova 3i
 - OS: [e.g. iOS8.1]  Android 8.1.0
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] 84.0.4147.89

**Additional context**

**Comment by rockzy3** [comment]
well am facing same issue

**Comment by TannerGabriel** [comment]
I'm sorry that you are facing problems. I will look into it as soon as possible.

**Comment by TannerGabriel** [comment]
It seems that I muted the video tag because of another issue I discovered a few months back. I have now taken a closer look at fixed the problem.

Please try it out and tell me if it also works for you and sorry for the late fix.

**Comment by piavgh** [comment]
@TannerGabriel : Thank you for checking on this.

If I remove the `muted` property in video tag and go to localhost:4000 (as a viewer), I can only see a black screen. 
So I guess that both `muted` and no muted cause different problems.

**Comment by TannerGabriel** [comment]
Yes that is what I was trying to say. I have a fix for that but it seems that I forgot to push it to Github yesterday (Very sorry for that).

I will push it in the evening and contact you after that.

**Comment by TannerGabriel** [comment]
There seems to be a general problem when it comes to audio and auto-playing in the browser. The browsers don't allow to play audio before the user has interacted with the website.

I have now fixed the problem by adding a simple button to enable audio, which needs to be clicked by the user. I know that this is not an intuitive solution by any means, but I think that it is okay for now. I will be on the lookout for a better solution and surely let you know if I find one.

In the meantime, you can use my fix or try one described in these resources:

- [Autoplay Policy Changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)
- [How to make audio autoplay on chrome](https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome)

If you find a great solution on your own, feel free to let me know.
