### ISSUE TITLE
1toN broadcast

### ISSUE THREAD

**Issue by yarekc** [TannerGabriel/WebRTC-Video-Broadcast#20]
I guess your solution is ok for 1toN where N<10 (since 1 client will deliver N streams and will lack of bandwidth quickly)
My question is: 

1) can we use TURN to force to relay ALL streams (and have N>100 streams for instance) ?
2) any solution other solution to have n>100 (like using a SFU server ?)

regards

**Comment by TannerGabriel** [comment]
Sorry for the late response I somehow missed this issue. That said you are right that the repository currently doesn't scale that well when adding a lot of users and that it would be better using a SFU server. This repository is meant for beginners that are new to WebRTC so I think that it would just complicate the current repo.

I'm currently working with  the [ION-SFU](https://github.com/pion/ion-sfu) server and plan on releasing a repository and article on that. Here you have an SFU with support for multiple rooms that scales really well with higher numbers of users.
