### ISSUE TITLE
Support for multiple Broadcast?

### ISSUE THREAD

**Issue by rohitcoder** [TannerGabriel/WebRTC-Video-Broadcast#21]
Hi You planned to implement support for multiple broadcast? Like i will open broadcast page and i will enter any random string as identifier and i will start broadcasting, when someone wants to watch that broadcast, they have to enter same random string which was used by broadcaster.

**Comment by TannerGabriel** [comment]
I plan on developing such an application at a later point, but this functionality will not be included in this repository.

As I'm currently working on other projects, it could take some time until that will happen.
