### ISSUE TITLE
not working when install on server

### ISSUE THREAD

**Issue by onli2** [TannerGabriel/WebRTC-Video-Broadcast#22]
when I installed it on ubuntu server 20.04 then tried running broadcat.html through the desktop the result was a blank page with a blank drop down audio and video menu.

**Comment by TannerGabriel** [comment]
It might be an indication that you do not have a camera and a microphone connected to your server. 

If not tell me and I will take a closer look at the problem.

**Comment by onli2** [comment]
my server on virtualbox, and it's connect to integrated camera
"integrated camera: integrated c"  /dev/video1

**Comment by TannerGabriel** [comment]
OK, but the application uses the camera of the user (the person accessing the website) and not the camera of the server hosting the application. If you have also connected a camera to your computer that is accessing the camera let me know and I will try to reproduce the problem.

**Comment by onli2** [comment]
not working, i"ve try both desktop and mobile

**Comment by TannerGabriel** [comment]
I'm really sorry, but I can currently not reproduce this issue. I tried it on three different devices with different operating systems (ubuntu 20.04, ubuntu 18.04, and Windows 10) and a few different cameras (integrated, USB), but I always receive a video when visiting `http://localhost:4000/broadcast.html`.
