### ISSUE TITLE
Doesn't work on my server

### ISSUE THREAD

**Issue by FerHernandezT** [TannerGabriel/WebRTC-Video-Broadcast#24]
I just published my code and it's not working, but on localhost I work very well.

I think it has to do with the stun or turn server, but I don't have much knowledge of this.
If you could advise me, it would be very helpful.

this is my setting:
const config = {
  iceServers: [
    { 
      "urls": "stun:stun.l.google.com:19302",
    },
    // { 
    //   "urls": "turn:TURN_IP?transport=tcp",
    //   "username": "TURN_USERNAME",
    //   "credential": "TURN_CREDENTIALS"
    // }
  ]
};

**Comment by TannerGabriel** [comment]
Yes, you first need to create a TURN server and then you can add the credentials in the code you posted above. If you don't know how to create a TURN server, I can recommend [this article](https://gabrieltanner.org/blog/turn-server).
