### ISSUE TITLE
Audio and Video is not enabling 

### ISSUE THREAD

**Issue by rishat5081** [TannerGabriel/WebRTC-Video-Broadcast#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

There is an error regarding to audio and video, they are not being signaled..

**Comment by TannerGabriel** [comment]
So you are saying that you cannot see the video that is sent by the broadcaster when accessing the main page on your mobile phone.

That can have various reasons, and I will test it out myself and see if I can reproduce this issue (I do not have iOS, but I will hopefully still be able to reproduce it on Android with Chrome).

For now, I would recommend adding a TURN server to the application if you are facing signaling problem.
