### ISSUE TITLE
how many users can view the stream please mention the maximum limit

### ISSUE THREAD

**Issue by jithinbabukmofficial** [TannerGabriel/WebRTC-Video-Broadcast#31]
please mention the how many connection it can handle simultaneously

**Comment by TannerGabriel** [comment]
I don't know the specific number, but the repository does not scale well and everything over 10 users in a session should be a problem. If you want to build an application that supports more users, I can recommend using an SFU (Selective Forwarding Unit), which scales a lot better.

I personally use the [ion-sfu](https://github.com/pion/ion-sfu), which is an open source SFU written in Golang. If you are interested, you can check out my article [here](https://gabrieltanner.org/blog/broadcasting-ion-sfu).

You can find out more about SFUs by reading this [paper](https://www.frozenmountain.com/hubfs/5%20-%20pdfs/frozenmountain-sfu-selective-forwarding-whitepaper.pdf).
