### ISSUE TITLE
how i can receive audio from broadcast?

### ISSUE THREAD

**Issue by Nemra1** [TannerGabriel/WebRTC-Video-Broadcast#4]
hello... am found ur project very useful and i have some question
how i can receive audio from broadcast in viewer page.... its only video screen and i cant heard any audio from another device in same network

**Comment by TannerGabriel** [comment]
The application is able to transfer audio and video data and should work fine.

I just tried it, and it worked fine for me. Could you provide more information and check if your microphone is connected.

**Comment by Nemra1** [comment]
Im try many times to get that work but no luck.. Maybe because am run as broadcast and viewer in same pc?

**Comment by TannerGabriel** [comment]
I just tried the same thing today and it worked. Are you sure that you are using the newest version of this repository?

You can get it using the following command in your repo directory:

```bash
git pull origin master
```

**Comment by Nemra1** [comment]
@TannerGabriel i will try again

**Comment by TbreezyF** [comment]
I think you may need to add `audio: true` as a MediaStream constraint
