### ISSUE TITLE
video orientation and resolution

### ISSUE THREAD

**Issue by realjanek** [TannerGabriel/WebRTC-Video-Broadcast#44]
**Is your feature request related to a problem? Please describe.**
I'm running the application on Raspberry Pi. The video is oriented upside down

**Describe the solution you'd like**
The API to change video orientation and resolution

**Describe alternatives you've considered**
Searching for APIs to resolve my issue

**Additional context**

**Comment by TannerGabriel** [comment]
Are you using a Raspberry Cam or a regular USB camera? Also, is the video upside down with the standard video software or just using WebRTC mediadevices?

**Comment by realjanek** [comment]
I am using raspicam https://www.raspberrypi.com/products/camera-module-v2/ , not a regular USB camera. When running on Windows with USB camera, the orientation is correct. Due to mechanical constraints, it would be good for me to be able to rotate the video. I am initially using your code as is without any modifications.
