### ISSUE TITLE
Capturestream on instead of camera

### ISSUE THREAD

**Issue by Rhenm091619** [TannerGabriel/WebRTC-Video-Broadcast#46]
Does it posible to share the capturestream instead of camera...

Which 
<VIDEO id =`vod`>
<Source>
Video here
<Source>
</video>

Var vod =d. getElementById('vod');

Vod.capturestream();

Then transmit it to other?

**Comment by TannerGabriel** [comment]
The code is not meant for that and I have never tried it myself. The easiest way to know is to try it using the code you provided above.

Note: It is possible to transfer a pre-recorded video using WebRTC but I have never done it in the way described above. I can provide some examples of this (mainly in Golang) if you are interested.

**Comment by Rhenm091619** [comment]
Okay, :)  case close I think its imposible
