### ISSUE TITLE
Code modification for video app

### ISSUE THREAD

**Issue by sesackey** [TannerGabriel/WebRTC-Video-Broadcast#6]
Hey, I really appreciate the work you put into your example of a video chat app with socket.io. and node.js. I have been trying to work out a way to incorporate your approach into adding a video chat application on an interactive online whiteboard project I have been working on. 

My main issue is that with your code, the watcher is a video element on another html file that has to be opened separately. What I want is to have both the broadcaster and watcher video elements on the same page, so I added the broadcaster and watcher code (with some modifications) into my code and deployed the app to heroku. The video streaming works fine when I open the tab as the broadcaster. However, it doesnt stream to the watchers video element when I open the second tab. Would appreciate any help you can offer, I know I havent gone into alot of detail but just wanted to give you a general idea of whats going on.

By the way my app has two video elements, so the way it works is that while one element is streaming the media from the webcam (my computer), the second element on the same page is streaming the media from a clients webcam somewhere else.

Looking forward to hearing back from you, thanks.

**Comment by TannerGabriel** [comment]
That sounds doable, but I will need more information and preferably the source code to tell really help you out here.

**Comment by sesackey** [comment]
Sure no prob. The files are attached below. The js code is titled video.js in the js folder. The html file is also included as well as the server side code. Thanks a lot. And let me know if you need any other material.

[videoapp2.zip](https://github.com/TannerGabriel/WebRTC-Video-Broadcast/files/4432520/videoapp2.zip)

**Comment by zabio8275** [comment]
thanks for your work 
i found this bug on firefox 75.0 (64-bit)

ICE failed, add a TURN server and see about:webrtc for more details

**Comment by sesackey** [comment]
> thanks for your work
> it works will on chrome but on fire fox there is an error (can't play broadcasted video)
> i found this bug on firefox 75.0 (64-bit)
> 
> on viewer page console error :
> ICE failed, add a TURN server and see about:webrtc for more details

Thanks for the input. I have looked over the code and it works with both chrome and firefox now. What I have found out so far is that the main issue is that the application works fine while testing on my macbook pro (Retina, 13-inch, Early 2015). However, when I broadcast from my macbook and open the second tab on my desktop (Windows 10), video element 1 streams without an issue on my macbook as the broadcaster. However, video element 2 doesn't stream on my windows computer. 

At this point I am guessing it may have something to do with the ios to windows connection. Not entirely sure and it doesnt really make much sense because I have tested with a friend who lives across the country and uses a macbook air and the connection works just fine on my windows, but for some reason when I repeat the test myself this issue appears. 

Ill continue to test with others remotely and if everything looks good I guess I'll take what I can get for now.

**Comment by zabio8275** [comment]
thank you @sesackey for your reply yes it works sometimes but not always and the other cases i did not test yet. 
hope you all the best.

**Comment by vino6665** [comment]
> > thanks for your work
> > it works will on chrome but on fire fox there is an error (can't play broadcasted video)
> > i found this bug on firefox 75.0 (64-bit)
> > on viewer page console error :
> > ICE failed, add a TURN server and see about:webrtc for more details
> 
> Thanks for the input. I have looked over the code and it works with both chrome and firefox now. What I have found out so far is that the main issue is that the application works fine while testing on my macbook pro (Retina, 13-inch, Early 2015). However, when I broadcast from my macbook and open the second tab on my desktop (Windows 10), video element 1 streams without an issue on my macbook as the broadcaster. However, video element 2 doesn't stream on my windows computer.
> 
> At this point I am guessing it may have something to do with the ios to windows connection. Not entirely sure and it doesnt really make much sense because I have tested with a friend who lives across the country and uses a macbook air and the connection works just fine on my windows, but for some reason when I repeat the test myself this issue appears.
> 
> Ill continue to test with others remotely and if everything looks good I guess I'll take what I can get for now.

hi...would you have solve the problem..if then could you send me the code..thanks...

**Comment by quantuminformation** [comment]
did you get the path
    <script src="/socket.io/socket.io.js"></script>

to work?

**Comment by quantuminformation** [comment]
nvm, its a signal magic thing
