### ISSUE TITLE
Broadcast video content freezes. Needs reload page to work again

### ISSUE THREAD

**Issue by Biavleren** [TannerGabriel/WebRTC-Video-Broadcast#63]
**Describe the bug**
After a while (on my setup it is ~30 min, ubuntu on a mini pc) the broadcast.html video feed will freeze and I have to reload page to make the video work again. The viewer.html gets the content immediately after reload on broadcast.html, so I believe the connection is ok.
Using a more powerful machine to broadcast video content, will expand the lifetime of video streaming before the video again will freeze and needs to reload page. On a thinkpad (windows 11) p14s chrome uses 1 gb of memory and the cpu is running 60%.
Some kind of memory leak... ?

**To Reproduce**
1. Clone repo.
2. npm install
3. localhost:4000/broadcast.html

**Expected behavior**
The video stream will stay consistent without the need of reloading or other maintanence.

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - CPU architecture: [intel celeron x86]

**Dependency versions:**
 - Nodejs version: [10.19.0]

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/WebRTC-Video-Broadcast/issues?q=is%3Aissue)

**Comment by Nemra1** [comment]
Any update for this issue?

**Comment by Biavleren** [comment]
Unfortunately not. I have been searching for alternatives and found the project of go2RTC https://github.com/AlexxIT/go2rtc.

My use case is a livestream embedded in webpage with low latency for controlling robots live.
