### ISSUE TITLE
help to watch the Broadcaster by name

### ISSUE THREAD

**Issue by Nemra1** [TannerGabriel/WebRTC-Video-Broadcast#7]
im looking for some way to add name to streamer and viewe by streamer name
for example
http://127.0.0.1/Broadcast/Broadcast.html?name=Ahmed
http://127.0.0.1/Broadcast/watch.html?host=Ahmed
I appreciate any help

**Comment by Hawkz69** [comment]
@Nemra1 
got some way? I have the same doubt

**Comment by Hawkz69** [comment]
@Nemra1 I managed to pass a parameter in the connection and then I passed this parameter to the events

https://stackoverflow.com/questions/43280613/set-username-in-socket-io-connection
